### ISSUE TITLE
Issue with everything

### ISSUE THREAD

**Issue by lolzvid** [lolzvid/undertale_techdemo#6]
Suddently, the collision and the rendering from the demo got f*cked up (I've revised the code too many times), and I can't really fix it.

Any help?

**Comment by Xavyrr** [comment]
I'll take a look at it tonight!

**Comment by hlixed** [comment]
Figured it out! In your refactoring, at the very end of render() you removed this:
// Swap sf2d framebuffers and wait for VBlank
sf2d_swapbuffers ();

I tested it, and adding that line back in makes it work again.

**Comment by lolzvid** [comment]
Wow, that's embarassing... Thanks a lot for the fix :wink:

Now back to business!

**Comment by Xavyrr** [comment]
Whoo hoo!
